<a href="https://colab.research.google.com/github/chandrakant1212/Descriptive-Statistivs-and-EDA/blob/main/Pandas_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Assignment

# Instructions for Pandas Assignment
---
Welcome to the Pandas Assignment! In this exercise, you will work with the CO2_Emissions_Canada2 dataset for Assignment your data manipulation and analysis skills using Pandas. Please follow the instructions below carefully:

1. **Understand the Dataset**: The dataset used in this assignment is related to the CO2_Emissions_Canada2. Familiarize yourself with the dataset's structure and content before starting.

2. **Read Each Question Thoroughly**: Each question in this assignment is designed to test different Pandas functionalities. Make sure you understand the requirements of each question before you begin coding.

3. **Write Your Code in the Provided Cells**: For each question, a code cell is provided where you should write your solution. Do not modify any other cells or sections of the notebook.

4. **Execute Your Code**: After writing your code in each cell, run the cell to check if your code produces the expected results. Verify that the output matches the requirements specified in the question.

5. **Complete All Questions**: Ensure that you attempt and complete all the questions provided in the notebook. Each question is designed to test different Pandas skills and concepts.

6. **Review Your Work**: Before submitting, double-check your answers and make sure all questions are addressed. Ensure that the notebook runs without errors and that all outputs are correct.

7. **Download Your Notebook**: Once you have completed all the questions and verified your solutions, download the notebook file (.ipynb). You can do this by selecting `File` > `Download` > `Download .ipynb` from the Google Colab menu.

8. **Submit Your Assignment**: Upload the downloaded .ipynb file to the designated learning platform for submission.

9. **Verify Submission**: Ensure that you have uploaded the correct file and that it is not corrupted. If you encounter any issues with the file, you may need to resubmit.

---

Good luck with your Assignment!

In [1]:
import numpy as np
import pandas as pd

co2_emission = "https://s3.ap-south-1.amazonaws.com/new-assets.ccbp.in/frontend/content/aiml/classical-ml/CO2_Emissions_Canada2.csv"

data = pd.read_csv(co2_emission)
data.head()

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196.0
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221.0
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136.0
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255.0
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244.0

**1. What is the median engine size for each type of `transmission`?**

In [2]:
# write your code here
# Group by 'Transmission' and calculate the median engine size
median_engine_size = data.groupby('Transmission')['Engine Size(L)'].median()
median_engine_size

Transmission
A10     6.2
A4      4.3
A5      3.8
A6      3.6
A7      4.0
A8      3.6
A9      3.0
AM5     1.0
AM6     2.0
AM7     3.0
AM8     3.0
AM9     3.5
AS10    3.5
AS4     2.4
AS5     4.0
AS6     2.5
AS7     3.7
AS8     3.0
AS9     3.5
AV      2.0
AV10    3.5
AV6     2.5
AV7     2.0
AV8     2.0
M5      1.8
M6      2.0
M7      3.4
Name: Engine Size(L), dtype: float64

---
**2. What is the correlation between CO2 emissions (g/km) and fuel consumption in the city (L/100 km)?**

In [4]:
# write your code here
co2_correlation = data['CO2 Emissions(g/km)'].corr(data['Fuel Consumption City (L/100 km)'])
co2_correlation

np.float64(0.9195626820357139)

---
**3. What is the average CO2 emissions (in g/km) for vehicles in the "TWO-SEATER" class?**

In [5]:
# write your code here
two_seater_mean =  data[data['Vehicle Class'] == 'TWO-SEATER']['CO2 Emissions(g/km)'].mean()
two_seater_mean

np.float64(277.454347826087)

---
**4.What is the average fuel consumption (in L/100 km) for vehicles of the make "DODGE" in the dataset?**

In [6]:
# write your code here
avg_fuel_by_class = data[data['Make'] == 'DODGE']['Fuel Consumption Comb (L/100 km)'].mean()
avg_fuel_by_class

np.float64(12.510162601626014)

---
**5.What is the overall average CO2 emissions (in g/km) for vehicles of the make "DODGE" in the dataset?**

In [7]:
# write your code here
overall_avg_co2 = data[data['Make'] == 'DODGE']['CO2 Emissions(g/km)'].mean()
overall_avg_co2

np.float64(276.3617886178862)


---
**6.Find out which combination of vehicle class and fuel type offers best fuel efficiency.**

In [8]:
# Calculate the average fuel consumption for each (Vehicle Class, Fuel Type) combination
avg_fuel_combo = data.groupby(['Vehicle Class', 'Fuel Type'])['Fuel Consumption Comb (L/100 km)'].mean()

# get only the first row in the aggregated output
# Sort by fuel consumption to find the lowest
best_efficiency = avg_fuel_combo.sort_values().index[0]
best_efficiency

('SUBCOMPACT', 'D')

---
**7.Find out which combination of number of cylinders and fuel type has highest carbon emissions.**

In [9]:
# Group by Cylinders and Fuel Type and find mean CO2 emissions
avg_co2_by_cyl_fuel = data.groupby(['Cylinders', 'Fuel Type'])['CO2 Emissions(g/km)'].mean()

# Sort by CO2 emissions in descending order
highest_co2_combo = avg_co2_by_cyl_fuel.sort_values(ascending=False).index[0]
highest_co2_combo

(np.int64(16), 'Z')

---
**8.How can you filter the dataset to find model with given details where SUV vehicles of the make "DODGE," and CO2 emissions of 255.0 g/km?**

In [16]:
# write your code here
small_suv_high =  data[(data['Vehicle Class'] == 'SUV') & (data['Make'] == 'DODGE') & (data['CO2 Emissions(g/km)'] == 255.0)]
small_suv_high

Empty DataFrame
Columns: [Make, Model, Vehicle Class, Engine Size(L), Cylinders, Transmission, Fuel Type, Fuel Consumption City (L/100 km), Fuel Consumption Hwy (L/100 km), Fuel Consumption Comb (L/100 km), Fuel Consumption Comb (mpg), CO2 Emissions(g/km)]
Index: []

---
**9.Calculate the interquartile range for co2 emissions by small suvs.**
1. Step 1 : Filter the data for vehicle class small suv
2. step 2 : Calculate quantile 1 for co2 emission
3. step 3 : Calculate quantile 3 for co2 emmision
4. step 4 : calculate the IQR using step 2 and step 4.

In [17]:
# write your code here
small_suv = data[data['Vehicle Class'] == 'SUV-SMALL']
Q1 = small_suv['CO2 Emissions(g/km)'].quantile(0.25)
Q3 = small_suv['CO2 Emissions(g/km)'].quantile(0.75)
IQR = Q3 - Q1
IQR

np.float64(nan)

---
**10.What is the average fuel consumption in the city (L/100 km) for all vehicles in the dataset?**

In [18]:
# write your code here
mean_of_fuel = data['Fuel Consumption City (L/100 km)'].mean()
mean_of_fuel

np.float64(12.556533513879485)

# End!